-- =============================================================================
-- V1 — Core schema for WizardCD (Phase 4)
-- =============================================================================
-- Tables : applications, environment_configs, deployments,
--          deployment_states, audit_events
-- Type   : Forward-only migration. Once applied, edit only via V2+.
-- =============================================================================
--
-- Design notes
-- ------------
-- 1.  UUID primary keys for application-driven rows (applications,
--     environment_configs, deployments). The Java side already generates
--     UUIDs via UUID.randomUUID() — we let the app stay in control rather
--     than relying on a DB default (gen_random_uuid()). Simpler ownership.
--
-- 2.  BIGSERIAL primary keys for append-only event rows
--     (deployment_states, audit_events). They're ordered and queried by
--     creation time; we never reference them as foreign keys; a monotonic
--     bigint matches that access pattern better than UUIDs.
--
-- 3.  TIMESTAMP WITH TIME ZONE everywhere. Java's Instant is UTC by
--     definition; storing as TIMESTAMP WITH TIME ZONE preserves it. The matching
--     application-dev.yaml block sets hibernate.jdbc.time_zone: UTC so
--     the Java→PostgreSQL round-trip is timezone-neutral.
--
-- 4.  JSONB for config_snapshot (deployments) and details (audit_events).
--     PostgreSQL's JSONB allows future indexed queries like:
--       SELECT * FROM deployments WHERE config_snapshot->>'mainClass' = '...'
--     We pay a small storage overhead for that flexibility.
--
-- 5.  Foreign-key cascade rules chosen to preserve history:
--      • CASCADE   when the child is meaningless without the parent
--                  (environment_configs → applications, deployment_states → deployments)
--      • SET NULL  when the child has independent historical value
--                  (deployments.app_id, deployments.env_config_id —
--                   preserves the deployment record even if you later
--                   delete the app registry entry)
--
-- 6.  Status / job_type / env_name / deployment_strategy left as plain
--     VARCHAR without CHECK constraints. Java enums (JobStatus,
--     JobExecutionStateStatus) evolve over time; we don't want DB
--     migrations every time we add a state. The app layer enforces.
--
-- 7.  updated_at auto-managed via JPA @PreUpdate callbacks on the
--     entity classes (Application, EnvironmentConfig) in Stage 3.
--     Earlier draft used a PL/pgSQL trigger, but PL/pgSQL is
--     PostgreSQL-specific and breaks H2 in tests. JPA @PreUpdate gives
--     us the same behaviour with no SQL portability cost.
--
-- 8.  Indexes are plain (no partial WHERE clauses) because H2 doesn't
--     support partial indexes. The size + performance impact on our
--     table sizes is negligible.
-- =============================================================================


-- =============================================================================
-- 1. applications — the central app registry
-- =============================================================================
-- One row per deployable application. Phase 5 hangs the registry UI off this.
-- Phase 4 inserts a row lazily on first deployment of a new appName.

CREATE TABLE applications (
    id          UUID         PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  applications              IS 'Central registry of deployable applications (one row per unique appName).';
COMMENT ON COLUMN applications.id           IS 'Application UUID — generated by Java (UUID.randomUUID()).';
COMMENT ON COLUMN applications.name         IS 'Unique app name as entered in the deploy wizard, e.g. "eureka-registry-ms".';
COMMENT ON COLUMN applications.description  IS 'Human-readable description, NULL allowed. Populated via Phase 5 registry UI.';
COMMENT ON COLUMN applications.created_at   IS 'When the application was first registered (first deployment of this name).';
COMMENT ON COLUMN applications.updated_at   IS 'When the application metadata was last modified (auto-updated by trigger).';


-- =============================================================================
-- 2. environment_configs — per-app, per-env saved deployment settings
-- =============================================================================
-- The "app registry" Phase 5 feature lives here. Phase 4 only writes
-- snapshots into deployments.config_snapshot; we don't yet populate this
-- table from the deploy wizard. It exists now so the FK columns on
-- deployments can be added at the same time and Phase 5 doesn't need an
-- ALTER TABLE later.

CREATE TABLE environment_configs (
    id                  UUID         PRIMARY KEY,
    app_id              UUID         NOT NULL,
    env_name            VARCHAR(20)  NOT NULL,               -- DEV | SIT | UAT | PROD (or custom)
    ssh_user            VARCHAR(100) NOT NULL,
    ssh_host            VARCHAR(255) NOT NULL,
    ssh_port            INTEGER      NOT NULL DEFAULT 22,
    java_command        VARCHAR(500) NOT NULL,
    java_version        VARCHAR(10),
    target_base_path    VARCHAR(500) NOT NULL,
    run_as_user         VARCHAR(100) NOT NULL,
    server_port         INTEGER      NOT NULL,
    main_class          VARCHAR(500),
    jar_name            VARCHAR(255),
    lib_path            VARCHAR(255) NOT NULL DEFAULT '',    -- '' = fat JAR, 'lib' = thin JAR
    xms                 VARCHAR(20),
    xmx                 VARCHAR(20),
    extra_jvm_opts      TEXT,                                 -- JSON array of strings
    max_log_size        VARCHAR(20)  NOT NULL DEFAULT '10m',
    max_log_files       INTEGER      NOT NULL DEFAULT 10,
    perform_backup      BOOLEAN      NOT NULL DEFAULT TRUE,
    max_backups         INTEGER      NOT NULL DEFAULT 5,
    stability_window    INTEGER      NOT NULL DEFAULT 20,    -- seconds (5..120)
    deployment_strategy VARCHAR(30)  NOT NULL DEFAULT 'in_place',  -- future: blue_green, canary, rolling
    created_at          TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT NOW(),

    -- Each (app, env) pair has at most one saved config
    CONSTRAINT uq_environment_configs_app_env UNIQUE (app_id, env_name),

    -- Delete an app → its env configs go with it (env config has no
    -- meaning without its parent app)
    CONSTRAINT fk_environment_configs_app
        FOREIGN KEY (app_id) REFERENCES applications(id) ON DELETE CASCADE
);

COMMENT ON TABLE  environment_configs IS 'Saved per-app, per-env deployment settings (Phase 5 registry).';

COMMENT ON COLUMN environment_configs.id                  IS 'Environment config UUID.';
COMMENT ON COLUMN environment_configs.app_id              IS 'FK → applications(id). CASCADE on delete.';
COMMENT ON COLUMN environment_configs.env_name            IS 'Environment name — DEV / SIT / UAT / PROD, or a custom per-app value.';
COMMENT ON COLUMN environment_configs.ssh_user            IS 'Linux user the runner SSHes in as (e.g. "deploy").';
COMMENT ON COLUMN environment_configs.ssh_host            IS 'Target IP or hostname.';
COMMENT ON COLUMN environment_configs.ssh_port            IS 'SSH port (default 22).';
COMMENT ON COLUMN environment_configs.java_command        IS 'Absolute path to the java binary on the target VM.';
COMMENT ON COLUMN environment_configs.java_version        IS 'Java major version, e.g. "21", "25". Optional.';
COMMENT ON COLUMN environment_configs.target_base_path    IS 'Root directory on target VM under which app dirs live.';
COMMENT ON COLUMN environment_configs.run_as_user         IS 'OS user the deployed app process runs as.';
COMMENT ON COLUMN environment_configs.server_port         IS 'Port the deployed application listens on.';
COMMENT ON COLUMN environment_configs.main_class          IS 'Spring Boot main class (FQCN). NULL for fat JAR (uses JarLauncher).';
COMMENT ON COLUMN environment_configs.jar_name            IS 'Name of the deployed JAR (e.g. "eureka-registry-ms.jar").';
COMMENT ON COLUMN environment_configs.lib_path            IS '"" = fat JAR, "lib" = thin JAR with external dependencies.';
COMMENT ON COLUMN environment_configs.xms                 IS 'JVM initial heap (-Xms), e.g. "512m". NULL = JVM default.';
COMMENT ON COLUMN environment_configs.xmx                 IS 'JVM max heap (-Xmx), e.g. "2g". NULL = JVM default.';
COMMENT ON COLUMN environment_configs.extra_jvm_opts      IS 'Extra JVM args as a JSON array of strings.';
COMMENT ON COLUMN environment_configs.max_log_size        IS 'Tanuki wrapper log rotation size (e.g. "10m").';
COMMENT ON COLUMN environment_configs.max_log_files       IS 'Number of rotated log files to retain.';
COMMENT ON COLUMN environment_configs.perform_backup      IS 'Take a release backup before deploying.';
COMMENT ON COLUMN environment_configs.max_backups         IS 'How many backups to keep (1..5).';
COMMENT ON COLUMN environment_configs.stability_window    IS 'Post-start health check duration in seconds (5..120).';
COMMENT ON COLUMN environment_configs.deployment_strategy IS 'Strategy ID. Phase 4 only supports "in_place". Phase 8 adds blue_green / canary / rolling.';


-- =============================================================================
-- 3. deployments — every job ever run (deploy, redeploy, rollback)
-- =============================================================================
-- The core table for Phase 4 — replaces the file-based status.json /
-- metadata.json / request.json triplet. Each row is one deployment job.

CREATE TABLE deployments (
    id              UUID         PRIMARY KEY,
    app_id          UUID,                                   -- nullable FK; SET NULL on app delete
    env_config_id   UUID,                                   -- nullable FK; SET NULL on env config delete
    app_name        VARCHAR(100) NOT NULL,                  -- denormalised for history preservation
    env_name        VARCHAR(20)  NOT NULL,                  -- denormalised for history preservation
    job_type        VARCHAR(20)  NOT NULL DEFAULT 'deploy', -- deploy | redeploy | rollback
    status          VARCHAR(30)  NOT NULL,                  -- CREATED, VALIDATING, ..., SUCCESS, FAILED, ABORTED
    config_snapshot JSONB,                                  -- full DeploymentRequest at time of deploy
    jar_name        VARCHAR(255),
    source_job_id   UUID,                                   -- for redeploy/rollback: original job
    workspace_path  VARCHAR(500),                           -- /opt/wizardcd/workspace/jobs/<id>
    created_at      TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMP WITH TIME ZONE,                            -- NULL while running
    created_by      VARCHAR(255),                           -- NULL until Phase 6 auth

    -- App + env FKs are nullable + SET NULL: a deployment's historical
    -- record survives even if you later prune the app registry.
    CONSTRAINT fk_deployments_app
        FOREIGN KEY (app_id) REFERENCES applications(id) ON DELETE SET NULL,
    CONSTRAINT fk_deployments_env_config
        FOREIGN KEY (env_config_id) REFERENCES environment_configs(id) ON DELETE SET NULL
);

COMMENT ON TABLE  deployments IS 'Every deployment job ever submitted — the core history table. Replaces status.json + metadata.json + request.json.';

COMMENT ON COLUMN deployments.id              IS 'Job UUID (matches what RunnerServiceImpl.runDeploy() generates).';
COMMENT ON COLUMN deployments.app_id          IS 'FK → applications(id), nullable. SET NULL on app delete to preserve history.';
COMMENT ON COLUMN deployments.env_config_id   IS 'FK → environment_configs(id), nullable. SET NULL on env config delete.';
COMMENT ON COLUMN deployments.app_name        IS 'Denormalised app name — preserves the name even if the app row is deleted.';
COMMENT ON COLUMN deployments.env_name        IS 'Denormalised env name — DEV / SIT / UAT / PROD or custom.';
COMMENT ON COLUMN deployments.job_type        IS '"deploy", "redeploy", or "rollback". Defaults to "deploy" for backward compat with old jobs.';
COMMENT ON COLUMN deployments.status          IS 'Lifecycle state — see com.ebb.wizardcd.runner.enums.JobStatus for canonical values.';
COMMENT ON COLUMN deployments.config_snapshot IS 'Full DeploymentRequest at the time of deploy (JSONB). Used for redeploy replay.';
COMMENT ON COLUMN deployments.jar_name        IS 'Original JAR filename uploaded by the user.';
COMMENT ON COLUMN deployments.source_job_id   IS 'For redeploy/rollback jobs: the deployment this one was derived from.';
COMMENT ON COLUMN deployments.workspace_path  IS 'Filesystem path to the job workspace directory (where artifacts + logs live).';
COMMENT ON COLUMN deployments.created_at      IS 'When the job was submitted via POST /jobs.';
COMMENT ON COLUMN deployments.completed_at    IS 'When the job reached a terminal state (SUCCESS / FAILED / ABORTED). NULL while running.';
COMMENT ON COLUMN deployments.created_by      IS 'User who triggered the job. NULL until Phase 6 auth lands.';


-- =============================================================================
-- 4. deployment_states — append-only state transition history
-- =============================================================================
-- One row per state change. Sorting by timestamp reconstructs the lifecycle:
-- CREATED → VALIDATING → PREPARING_WORKSPACE → RUNNING → SUCCESS/FAILED/ABORTED.

CREATE TABLE deployment_states (
    id              BIGSERIAL    PRIMARY KEY,
    deployment_id   UUID         NOT NULL,
    status          VARCHAR(30)  NOT NULL,
    timestamp       TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT NOW(),

    -- Delete a deployment → drop its state history with it
    CONSTRAINT fk_deployment_states_deployment
        FOREIGN KEY (deployment_id) REFERENCES deployments(id) ON DELETE CASCADE
);

COMMENT ON TABLE  deployment_states              IS 'Append-only state transition log for deployments. One row per state change.';
COMMENT ON COLUMN deployment_states.id           IS 'Monotonic event id (BIGSERIAL).';
COMMENT ON COLUMN deployment_states.deployment_id IS 'FK → deployments(id). CASCADE on delete.';
COMMENT ON COLUMN deployment_states.status        IS 'Lifecycle state being entered at this point in time.';
COMMENT ON COLUMN deployment_states.timestamp     IS 'When the state was entered.';


-- =============================================================================
-- 5. audit_events — append-only platform audit log
-- =============================================================================
-- Independent of deployments — captures cross-cutting actions like
-- DEPLOY, REDEPLOY, ROLLBACK, ABORT, CONFIG_CHANGE, USER_LOGIN (Phase 6).
-- No FK to deployments: an audit row survives even if the referenced
-- deployment is deleted.

CREATE TABLE audit_events (
    id          BIGSERIAL    PRIMARY KEY,
    action      VARCHAR(50)  NOT NULL,                  -- DEPLOY, REDEPLOY, ROLLBACK, ABORT, CONFIG_CHANGE, ...
    resource    VARCHAR(100),                            -- e.g. "eureka-registry-ms/UAT" or job UUID
    details     JSONB,                                   -- free-form per-event detail
    created_by  VARCHAR(255),                            -- NULL until Phase 6 auth
    created_at  TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  audit_events            IS 'Append-only audit log for cross-cutting platform actions. Hash-chained in Phase 11 for tamper detection.';
COMMENT ON COLUMN audit_events.id         IS 'Monotonic event id (BIGSERIAL).';
COMMENT ON COLUMN audit_events.action     IS 'High-level action type, e.g. "DEPLOY", "REDEPLOY", "ROLLBACK", "ABORT", "CONFIG_CHANGE".';
COMMENT ON COLUMN audit_events.resource   IS 'Free-form resource identifier the action targeted, e.g. "<app>/<env>" or a job UUID.';
COMMENT ON COLUMN audit_events.details    IS 'Per-action detail payload (JSONB). Schema varies by action type.';
COMMENT ON COLUMN audit_events.created_by IS 'User who triggered the action. NULL until Phase 6 auth lands.';
COMMENT ON COLUMN audit_events.created_at IS 'When the action occurred.';


-- =============================================================================
-- 6. Indexes — tuned for the actual queries the UI makes
-- =============================================================================
-- Reads dominate writes by ~100x. Indexes optimise:
--   • Dashboard table (filter by env, status; sort by created_at DESC)
--   • Application page (all deployments for app X)
--   • Notification poll (recently changed jobs)
--   • Activity chart (last 7 days)
--   • Audit log scrolling (recent events)
--
-- We do NOT add an index on env_name alone — env cardinality is ~4, so a
-- standalone index is less efficient than a sequential scan for "all UAT
-- jobs". The composite (app_name, env_name) covers the realistic case
-- ("eureka-registry-ms UAT jobs").
-- =============================================================================

CREATE INDEX idx_deployments_app_env       ON deployments (app_name, env_name);
CREATE INDEX idx_deployments_status        ON deployments (status);
CREATE INDEX idx_deployments_created_at    ON deployments (created_at DESC);
CREATE INDEX idx_deployments_app_id        ON deployments (app_id);
CREATE INDEX idx_deployments_env_config_id ON deployments (env_config_id);
CREATE INDEX idx_deployments_source_job_id ON deployments (source_job_id);

CREATE INDEX idx_deployment_states_deployment_id ON deployment_states (deployment_id, timestamp);

-- environment_configs already has UNIQUE(app_id, env_name) which doubles
-- as a btree index; no separate index needed.

CREATE INDEX idx_audit_events_created_at ON audit_events (created_at DESC);
CREATE INDEX idx_audit_events_action     ON audit_events (action);
