package com.ebb.wizardcd.runner.dto;

import com.ebb.wizardcd.runner.enums.JobExecutionStateStatus;
import com.ebb.wizardcd.runner.enums.JobStatus;

import java.time.Instant;
import java.util.List;

public class JobResponse {

    // Unique job identifier generated by control plane
    private String jobId;

    // Lifecycle state (CREATED -> RUNNING -> SUCCESS etc.)
    private JobStatus jobStatus;

    // Execution state snapshot (RECEIVED, WORKSPACE_READY, etc.)
    private JobExecutionStateStatus executionState;

    // Ordered lifecycle-state transitions with timestamps (for the timeline panel)
    private List<JobExecutionStatus.StateTransition> stateHistory;

    // From metadata.json — populated in the status endpoint
    private String application;
    private String environment;
    private Instant createdAt;

    public JobResponse(String jobId,
                       JobStatus jobStatus,
                       JobExecutionStateStatus executionState) {
        this(jobId, jobStatus, executionState, null);
    }

    public JobResponse(String jobId,
                       JobStatus jobStatus,
                       JobExecutionStateStatus executionState,
                       List<JobExecutionStatus.StateTransition> stateHistory) {
        this.jobId = jobId;
        this.jobStatus = jobStatus;
        this.executionState = executionState;
        this.stateHistory = stateHistory;
    }

    public String getJobId() { return jobId; }

    public JobStatus getJobStatus() { return jobStatus; }

    public JobExecutionStateStatus getExecutionState() { return executionState; }

    public List<JobExecutionStatus.StateTransition> getStateHistory() { return stateHistory; }

    public String getApplication() { return application; }
    public void setApplication(String application) { this.application = application; }

    public String getEnvironment() { return environment; }
    public void setEnvironment(String environment) { this.environment = environment; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
}
