package com.ebb.wizardcd.runner.dto;

import com.ebb.wizardcd.runner.enums.JobExecutionStateStatus;
import com.ebb.wizardcd.runner.enums.JobStatus;

public class JobResponse {

    // Unique job identifier generated by control plane
    private String jobId;

    // Lifecycle state (CREATED -> RUNNING -> SUCCESS etc.)
    private JobStatus jobStatus;

    // Execution state snapshot (RECEIVED, WORKSPACE_READY, etc.)
    private JobExecutionStateStatus executionState;

    public JobResponse(String jobId,
                       JobStatus jobStatus,
                       JobExecutionStateStatus executionState) {
        this.jobId = jobId;
        this.jobStatus = jobStatus;
        this.executionState = executionState;
    }

    public String getJobId() {
        return jobId;
    }

    public JobStatus getJobStatus() {
        return jobStatus;
    }

    public JobExecutionStateStatus getExecutionState() {
        return executionState;
    }
}
