package com.ebb.wizardcd.runner.service.impl;

import com.ebb.wizardcd.runner.dto.DeploymentRequest;
import com.ebb.wizardcd.runner.service.SshKeyService;
import com.ebb.wizardcd.runner.service.YamlGenerationService;
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;
import org.springframework.stereotype.Service;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.ebb.wizardcd.runner.config.ApplicationConstants.WORKSPACE_CONFIG_NAME;

@Service
public class YamlGenerationServiceImpl implements YamlGenerationService {

    // Dedicated YAML serializer used only for deployment-config generation
    private final YAMLMapper yamlMapper = new YAMLMapper();

    // Resolves the per-environment private key path for the SSH deployment block
    private final SshKeyService sshKeyService;

    public YamlGenerationServiceImpl(SshKeyService sshKeyService) {
        this.sshKeyService = sshKeyService;
    }

    @Override
    public Path generateYaml(String jobId, DeploymentRequest request, String artifactFileName, Path inputDir) {
        try {

            // Container for all sections under a specific environment
            Map<String, Object> appSection = new HashMap<>();

            // Application identity block (core runtime identity)
            appSection.put("app", Map.of(
                    "name", request.getAppName(),
                    "jar_name", artifactFileName,
                    "main_class", request.getMainClass()
            ));

            // Java runtime configuration block
            appSection.put("java", Map.of(
                    "command", request.getJavaCommand(),
                    "version", request.getJavaVersion()
            ));

            // JVM memory and tuning configuration
            appSection.put("jvm", Map.of(
                    "xms", request.getXms(),
                    "xmx", request.getXmx(),
                    "new_ratio", request.getNewRatio(),
                    "extra_opts", request.getExtraOpts() == null ? List.of() : request.getExtraOpts()
            ));

            // Runtime execution properties
            appSection.put("runtime", Map.of(
                    "run_as_user", request.getRunAsUser(),
                    "server_port", request.getServerPort()
            ));

            // Log rotation configuration
            appSection.put("logging", Map.of(
                    "max_size", request.getMaxLogSize(),
                    "max_files", request.getMaxLogFiles()
            ));

            // Build input section generated by runner (never controlled by UI paths).
            // cert_paths entries contain {source, targetPath} — deploy.sh scps each
            // source directory (relative to INPUT_DIR) to its targetPath on the server.
            List<Map<String, String>> certPathList = new ArrayList<>();
            if (request.getCertPaths() != null) {
                for (var cp : request.getCertPaths()) {
                    if (cp.getSource() != null && !cp.getSource().isBlank()
                            && cp.getTargetPath() != null && !cp.getTargetPath().isBlank()) {
                        Map<String, String> entry = new HashMap<>();
                        entry.put("source", cp.getSource());
                        entry.put("targetPath", cp.getTargetPath());
                        certPathList.add(entry);
                    }
                }
            }

            // Build extra_dirs list — same structure as cert_paths
            List<Map<String, String>> extraDirList = new ArrayList<>();
            if (request.getExtraDirs() != null) {
                for (var ed : request.getExtraDirs()) {
                    if (ed.getDirName() != null && !ed.getDirName().isBlank()
                            && ed.getTargetPath() != null && !ed.getTargetPath().isBlank()) {
                        Map<String, String> entry = new HashMap<>();
                        entry.put("dir_name", ed.getDirName());
                        entry.put("target_path", ed.getTargetPath());
                        extraDirList.add(entry);
                    }
                }
            }

            Map<String, Object> buildSection = new HashMap<>();
            buildSection.put("project_base_path", inputDir.toAbsolutePath().toString());
            buildSection.put("jar_path", artifactFileName);
            buildSection.put("lib_path", request.getLibPath() == null ? "" : request.getLibPath());
            buildSection.put("extra_dirs", extraDirList);
            buildSection.put("cert_paths", certPathList);
            appSection.put("build", buildSection);

            // Deployment target configuration (Direct VM mode)
            // The private key path is resolved by SshKeyService from the environment field —
            // it is never supplied by the client to prevent path traversal attacks.
            String resolvedKeyPath = sshKeyService.getPrivateKeyPath(request.getEnvironment());
            appSection.put("deployment", Map.of(
                    "type", "direct_vm",
                    "ssh", Map.of(
                            "user", request.getSshUser(),
                            "host", request.getSshHost(),
                            "port", request.getSshPort(),
                            "privateKeyPath", resolvedKeyPath),
                    "target", Map.of("base_path", request.getTargetBasePath())
            ));

            // Backup policy configuration
            appSection.put("backup", Map.of(
                    "perform_backup", request.getPerformBackup(),
                    "max_backups", request.getMaxBackups()
            ));

            // Wrap environment layer (e.g., uat, prod)
            Map<String, Object> environmentWrapper = Map.of(request.getEnvironment(), appSection);

            // Wrap application layer dynamically (no hardcoding app names)
            Map<String, Object> appWrapper = Map.of(request.getAppName(), environmentWrapper);

            // Root YAML node
            Map<String, Object> root = Map.of("apps", appWrapper);

            // Resolve final YAML path inside workspace input directory
            Path targetConfig = inputDir.resolve(WORKSPACE_CONFIG_NAME);

            // Serialize structured map into YAML file
            yamlMapper.writerWithDefaultPrettyPrinter().writeValue(targetConfig.toFile(), root);

            // Return absolute path used by deploy.sh
            return targetConfig.toAbsolutePath();
        } catch (Exception e) {
            // Fail fast if YAML generation breaks
            throw new IllegalStateException("YAML generation failed for jobId=" + jobId + " Exception: " + e.getMessage());
        }
    }
}