package com.ebb.wizardcd.runner.service;

import java.util.UUID;

/**
 * Input record for {@link DeploymentPersistenceService#createDeployment}.
 *
 * <p>Carries everything needed to persist a brand-new deployment row plus
 * its initial {@code CREATED} state transition. Caller is responsible for
 * generating {@link #id} (matches the pattern used by
 * {@code RunnerServiceImpl.runDeploy()}).
 *
 * @param id              UUID generated by the caller (job id)
 * @param appName         denormalised app name as entered in the wizard
 * @param envName         environment name (DEV / SIT / UAT / PROD or custom)
 * @param jobType         {@code "deploy"} / {@code "redeploy"} / {@code "rollback"}
 * @param jarName         JAR filename uploaded by user, may be {@code null}
 * @param configSnapshot  serialised {@code DeploymentRequest} JSON (stored as
 *                        JSONB), may be {@code null} for legacy / migrated rows
 * @param sourceJobId     for redeploy/rollback jobs: the original deployment
 *                        this one was derived from. {@code null} otherwise.
 * @param workspacePath   filesystem path to the job workspace dir, may be {@code null}
 * @param createdBy       user who triggered the job, {@code null} until Phase 6 auth
 */
public record CreateDeploymentCommand(
        UUID id,
        String appName,
        String envName,
        String jobType,
        String jarName,
        String configSnapshot,
        UUID sourceJobId,
        String workspacePath,
        String createdBy
) {

    /** Convenience for the common "deploy" job type without optional fields. */
    public static CreateDeploymentCommand deploy(
            UUID id, String appName, String envName, String jarName,
            String configSnapshot, String workspacePath) {
        return new CreateDeploymentCommand(
                id, appName, envName, "deploy",
                jarName, configSnapshot,
                null, workspacePath, null);
    }
}
